// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { ExperimentsService, InstrumentsService, type Options, UsersService, UtilsService } from '../sdk.gen';
import type { ExperimentsCreateExperimentData, ExperimentsCreateExperimentResponse, ExperimentsDeleteExperimentData, ExperimentsDeleteExperimentError, ExperimentsDeleteExperimentResponse, ExperimentsReadExperimentData, ExperimentsReadExperimentError, ExperimentsReadExperimentNamesData, ExperimentsReadExperimentNamesResponse, ExperimentsReadExperimentResponse, ExperimentsReadExperimentsData, ExperimentsReadExperimentsError, ExperimentsReadExperimentsResponse, ExperimentsUpdateExperimentData, ExperimentsUpdateExperimentError, ExperimentsUpdateExperimentResponse, InstrumentsReadInstrumentsData, InstrumentsReadInstrumentsResponse, UsersDeleteUserData, UsersDeleteUserError, UsersDeleteUserMeData, UsersDeleteUserMeResponse, UsersDeleteUserResponse, UsersReadUserByIdData, UsersReadUserByIdError, UsersReadUserByIdResponse, UsersReadUserMeData, UsersReadUserMeResponse, UsersReadUsersData, UsersReadUsersError, UsersReadUsersResponse, UsersUpdateUserData, UsersUpdateUserError, UsersUpdateUserMeData, UsersUpdateUserMeError, UsersUpdateUserMeResponse, UsersUpdateUserResponse, UtilsHealthCheckData, UtilsHealthCheckResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const usersReadUsersQueryKey = (options?: Options<UsersReadUsersData>) => createQueryKey('usersReadUsers', options);

/**
 * Read Users
 *
 * Retrieve users.
 */
export const usersReadUsersOptions = (options?: Options<UsersReadUsersData>) => queryOptions<UsersReadUsersResponse, AxiosError<UsersReadUsersError>, UsersReadUsersResponse, ReturnType<typeof usersReadUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UsersService.usersReadUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersReadUsersQueryKey(options)
});

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const usersDeleteUserMeMutation = (options?: Partial<Options<UsersDeleteUserMeData>>): UseMutationOptions<UsersDeleteUserMeResponse, AxiosError<DefaultError>, Options<UsersDeleteUserMeData>> => {
    const mutationOptions: UseMutationOptions<UsersDeleteUserMeResponse, AxiosError<DefaultError>, Options<UsersDeleteUserMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await UsersService.usersDeleteUserMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersReadUserMeQueryKey = (options?: Options<UsersReadUserMeData>) => createQueryKey('usersReadUserMe', options);

/**
 * Read User Me
 *
 * Get current user.
 */
export const usersReadUserMeOptions = (options?: Options<UsersReadUserMeData>) => queryOptions<UsersReadUserMeResponse, AxiosError<DefaultError>, UsersReadUserMeResponse, ReturnType<typeof usersReadUserMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UsersService.usersReadUserMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersReadUserMeQueryKey(options)
});

/**
 * Update User Me
 *
 * Update own user.
 */
export const usersUpdateUserMeMutation = (options?: Partial<Options<UsersUpdateUserMeData>>): UseMutationOptions<UsersUpdateUserMeResponse, AxiosError<UsersUpdateUserMeError>, Options<UsersUpdateUserMeData>> => {
    const mutationOptions: UseMutationOptions<UsersUpdateUserMeResponse, AxiosError<UsersUpdateUserMeError>, Options<UsersUpdateUserMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await UsersService.usersUpdateUserMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User
 *
 * Delete a user.
 */
export const usersDeleteUserMutation = (options?: Partial<Options<UsersDeleteUserData>>): UseMutationOptions<UsersDeleteUserResponse, AxiosError<UsersDeleteUserError>, Options<UsersDeleteUserData>> => {
    const mutationOptions: UseMutationOptions<UsersDeleteUserResponse, AxiosError<UsersDeleteUserError>, Options<UsersDeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await UsersService.usersDeleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersReadUserByIdQueryKey = (options: Options<UsersReadUserByIdData>) => createQueryKey('usersReadUserById', options);

/**
 * Read User By Id
 *
 * Get a specific user by id.
 */
export const usersReadUserByIdOptions = (options: Options<UsersReadUserByIdData>) => queryOptions<UsersReadUserByIdResponse, AxiosError<UsersReadUserByIdError>, UsersReadUserByIdResponse, ReturnType<typeof usersReadUserByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UsersService.usersReadUserById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersReadUserByIdQueryKey(options)
});

/**
 * Update User
 *
 * Update a user.
 */
export const usersUpdateUserMutation = (options?: Partial<Options<UsersUpdateUserData>>): UseMutationOptions<UsersUpdateUserResponse, AxiosError<UsersUpdateUserError>, Options<UsersUpdateUserData>> => {
    const mutationOptions: UseMutationOptions<UsersUpdateUserResponse, AxiosError<UsersUpdateUserError>, Options<UsersUpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await UsersService.usersUpdateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const utilsHealthCheckQueryKey = (options?: Options<UtilsHealthCheckData>) => createQueryKey('utilsHealthCheck', options);

/**
 * Health Check
 */
export const utilsHealthCheckOptions = (options?: Options<UtilsHealthCheckData>) => queryOptions<UtilsHealthCheckResponse, AxiosError<DefaultError>, UtilsHealthCheckResponse, ReturnType<typeof utilsHealthCheckQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UtilsService.utilsHealthCheck({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: utilsHealthCheckQueryKey(options)
});

export const experimentsReadExperimentNamesQueryKey = (options?: Options<ExperimentsReadExperimentNamesData>) => createQueryKey('experimentsReadExperimentNames', options);

/**
 * Read Experiment Names
 *
 * Retrieve all experiment names.
 */
export const experimentsReadExperimentNamesOptions = (options?: Options<ExperimentsReadExperimentNamesData>) => queryOptions<ExperimentsReadExperimentNamesResponse, AxiosError<DefaultError>, ExperimentsReadExperimentNamesResponse, ReturnType<typeof experimentsReadExperimentNamesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ExperimentsService.experimentsReadExperimentNames({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: experimentsReadExperimentNamesQueryKey(options)
});

export const experimentsReadExperimentsQueryKey = (options?: Options<ExperimentsReadExperimentsData>) => createQueryKey('experimentsReadExperiments', options);

/**
 * Read Experiments
 *
 * Retrieve experiments. Superusers see all; others see only experiments
 * where they are listed as a player.
 */
export const experimentsReadExperimentsOptions = (options?: Options<ExperimentsReadExperimentsData>) => queryOptions<ExperimentsReadExperimentsResponse, AxiosError<ExperimentsReadExperimentsError>, ExperimentsReadExperimentsResponse, ReturnType<typeof experimentsReadExperimentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ExperimentsService.experimentsReadExperiments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: experimentsReadExperimentsQueryKey(options)
});

/**
 * Create Experiment
 *
 * Create new experiment.
 */
export const experimentsCreateExperimentMutation = (options?: Partial<Options<ExperimentsCreateExperimentData>>): UseMutationOptions<ExperimentsCreateExperimentResponse, AxiosError<DefaultError>, Options<ExperimentsCreateExperimentData>> => {
    const mutationOptions: UseMutationOptions<ExperimentsCreateExperimentResponse, AxiosError<DefaultError>, Options<ExperimentsCreateExperimentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ExperimentsService.experimentsCreateExperiment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Experiment
 *
 * Delete an experiment.
 */
export const experimentsDeleteExperimentMutation = (options?: Partial<Options<ExperimentsDeleteExperimentData>>): UseMutationOptions<ExperimentsDeleteExperimentResponse, AxiosError<ExperimentsDeleteExperimentError>, Options<ExperimentsDeleteExperimentData>> => {
    const mutationOptions: UseMutationOptions<ExperimentsDeleteExperimentResponse, AxiosError<ExperimentsDeleteExperimentError>, Options<ExperimentsDeleteExperimentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ExperimentsService.experimentsDeleteExperiment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const experimentsReadExperimentQueryKey = (options: Options<ExperimentsReadExperimentData>) => createQueryKey('experimentsReadExperiment', options);

/**
 * Read Experiment
 *
 * Get experiment by ID (name). Reads directly from the per-experiment database.
 */
export const experimentsReadExperimentOptions = (options: Options<ExperimentsReadExperimentData>) => queryOptions<ExperimentsReadExperimentResponse, AxiosError<ExperimentsReadExperimentError>, ExperimentsReadExperimentResponse, ReturnType<typeof experimentsReadExperimentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ExperimentsService.experimentsReadExperiment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: experimentsReadExperimentQueryKey(options)
});

/**
 * Update Experiment
 *
 * Update an experiment.
 */
export const experimentsUpdateExperimentMutation = (options?: Partial<Options<ExperimentsUpdateExperimentData>>): UseMutationOptions<ExperimentsUpdateExperimentResponse, AxiosError<ExperimentsUpdateExperimentError>, Options<ExperimentsUpdateExperimentData>> => {
    const mutationOptions: UseMutationOptions<ExperimentsUpdateExperimentResponse, AxiosError<ExperimentsUpdateExperimentError>, Options<ExperimentsUpdateExperimentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ExperimentsService.experimentsUpdateExperiment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const instrumentsReadInstrumentsQueryKey = (options?: Options<InstrumentsReadInstrumentsData>) => createQueryKey('instrumentsReadInstruments', options);

/**
 * Read Instruments
 *
 * Return each distinct non-null instrument together with the number of
 * experiments the current user can access under that instrument.
 */
export const instrumentsReadInstrumentsOptions = (options?: Options<InstrumentsReadInstrumentsData>) => queryOptions<InstrumentsReadInstrumentsResponse, AxiosError<DefaultError>, InstrumentsReadInstrumentsResponse, ReturnType<typeof instrumentsReadInstrumentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await InstrumentsService.instrumentsReadInstruments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: instrumentsReadInstrumentsQueryKey(options)
});
