// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ExperimentsCreateExperimentData, ExperimentsCreateExperimentResponses, ExperimentsDeleteExperimentData, ExperimentsDeleteExperimentErrors, ExperimentsDeleteExperimentResponses, ExperimentsReadExperimentData, ExperimentsReadExperimentErrors, ExperimentsReadExperimentNamesData, ExperimentsReadExperimentNamesResponses, ExperimentsReadExperimentResponses, ExperimentsReadExperimentsData, ExperimentsReadExperimentsErrors, ExperimentsReadExperimentsResponses, ExperimentsUpdateExperimentData, ExperimentsUpdateExperimentErrors, ExperimentsUpdateExperimentResponses, ItemsCreateItemData, ItemsCreateItemErrors, ItemsCreateItemResponses, ItemsDeleteItemData, ItemsDeleteItemErrors, ItemsDeleteItemResponses, ItemsReadItemData, ItemsReadItemErrors, ItemsReadItemResponses, ItemsReadItemsData, ItemsReadItemsErrors, ItemsReadItemsResponses, ItemsUpdateItemData, ItemsUpdateItemErrors, ItemsUpdateItemResponses, UsersDeleteUserData, UsersDeleteUserErrors, UsersDeleteUserMeData, UsersDeleteUserMeResponses, UsersDeleteUserResponses, UsersReadUserByIdData, UsersReadUserByIdErrors, UsersReadUserByIdResponses, UsersReadUserMeData, UsersReadUserMeResponses, UsersReadUsersData, UsersReadUsersErrors, UsersReadUsersResponses, UsersUpdateUserData, UsersUpdateUserErrors, UsersUpdateUserMeData, UsersUpdateUserMeErrors, UsersUpdateUserMeResponses, UsersUpdateUserResponses, UtilsHealthCheckData, UtilsHealthCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UsersService {
    /**
     * Read Users
     *
     * Retrieve users.
     */
    public static usersReadUsers<ThrowOnError extends boolean = false>(options?: Options<UsersReadUsersData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersReadUsersResponses, UsersReadUsersErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/',
            ...options
        });
    }
    
    /**
     * Delete User Me
     *
     * Delete own user.
     */
    public static usersDeleteUserMe<ThrowOnError extends boolean = false>(options?: Options<UsersDeleteUserMeData, ThrowOnError>) {
        return (options?.client ?? client).delete<UsersDeleteUserMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Read User Me
     *
     * Get current user.
     */
    public static usersReadUserMe<ThrowOnError extends boolean = false>(options?: Options<UsersReadUserMeData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersReadUserMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Update User Me
     *
     * Update own user.
     */
    public static usersUpdateUserMe<ThrowOnError extends boolean = false>(options: Options<UsersUpdateUserMeData, ThrowOnError>) {
        return (options.client ?? client).patch<UsersUpdateUserMeResponses, UsersUpdateUserMeErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete User
     *
     * Delete a user.
     */
    public static usersDeleteUser<ThrowOnError extends boolean = false>(options: Options<UsersDeleteUserData, ThrowOnError>) {
        return (options.client ?? client).delete<UsersDeleteUserResponses, UsersDeleteUserErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Read User By Id
     *
     * Get a specific user by id.
     */
    public static usersReadUserById<ThrowOnError extends boolean = false>(options: Options<UsersReadUserByIdData, ThrowOnError>) {
        return (options.client ?? client).get<UsersReadUserByIdResponses, UsersReadUserByIdErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Update User
     *
     * Update a user.
     */
    public static usersUpdateUser<ThrowOnError extends boolean = false>(options: Options<UsersUpdateUserData, ThrowOnError>) {
        return (options.client ?? client).patch<UsersUpdateUserResponses, UsersUpdateUserErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     */
    public static utilsHealthCheck<ThrowOnError extends boolean = false>(options?: Options<UtilsHealthCheckData, ThrowOnError>) {
        return (options?.client ?? client).get<UtilsHealthCheckResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/utils/health-check/',
            ...options
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     *
     * Retrieve items.
     */
    public static itemsReadItems<ThrowOnError extends boolean = false>(options?: Options<ItemsReadItemsData, ThrowOnError>) {
        return (options?.client ?? client).get<ItemsReadItemsResponses, ItemsReadItemsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/items/',
            ...options
        });
    }
    
    /**
     * Create Item
     *
     * Create new item.
     */
    public static itemsCreateItem<ThrowOnError extends boolean = false>(options: Options<ItemsCreateItemData, ThrowOnError>) {
        return (options.client ?? client).post<ItemsCreateItemResponses, ItemsCreateItemErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/items/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Item
     *
     * Delete an item.
     */
    public static itemsDeleteItem<ThrowOnError extends boolean = false>(options: Options<ItemsDeleteItemData, ThrowOnError>) {
        return (options.client ?? client).delete<ItemsDeleteItemResponses, ItemsDeleteItemErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/items/{id}',
            ...options
        });
    }
    
    /**
     * Read Item
     *
     * Get item by ID.
     */
    public static itemsReadItem<ThrowOnError extends boolean = false>(options: Options<ItemsReadItemData, ThrowOnError>) {
        return (options.client ?? client).get<ItemsReadItemResponses, ItemsReadItemErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/items/{id}',
            ...options
        });
    }
    
    /**
     * Update Item
     *
     * Update an item.
     */
    public static itemsUpdateItem<ThrowOnError extends boolean = false>(options: Options<ItemsUpdateItemData, ThrowOnError>) {
        return (options.client ?? client).put<ItemsUpdateItemResponses, ItemsUpdateItemErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/items/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ExperimentsService {
    /**
     * Read Experiment Names
     *
     * Retrieve all experiment names.
     */
    public static experimentsReadExperimentNames<ThrowOnError extends boolean = false>(options?: Options<ExperimentsReadExperimentNamesData, ThrowOnError>) {
        return (options?.client ?? client).get<ExperimentsReadExperimentNamesResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/experiments/names',
            ...options
        });
    }
    
    /**
     * Read Experiments
     *
     * Retrieve experiments. Superusers see all; others see only experiments
     * where they are listed as a player.
     */
    public static experimentsReadExperiments<ThrowOnError extends boolean = false>(options?: Options<ExperimentsReadExperimentsData, ThrowOnError>) {
        return (options?.client ?? client).get<ExperimentsReadExperimentsResponses, ExperimentsReadExperimentsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/experiments/',
            ...options
        });
    }
    
    /**
     * Create Experiment
     *
     * Create new experiment.
     */
    public static experimentsCreateExperiment<ThrowOnError extends boolean = false>(options?: Options<ExperimentsCreateExperimentData, ThrowOnError>) {
        return (options?.client ?? client).post<ExperimentsCreateExperimentResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/experiments/',
            ...options
        });
    }
    
    /**
     * Delete Experiment
     *
     * Delete an experiment.
     */
    public static experimentsDeleteExperiment<ThrowOnError extends boolean = false>(options: Options<ExperimentsDeleteExperimentData, ThrowOnError>) {
        return (options.client ?? client).delete<ExperimentsDeleteExperimentResponses, ExperimentsDeleteExperimentErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/experiments/{id}',
            ...options
        });
    }
    
    /**
     * Read Experiment
     *
     * Get experiment by ID (name). Reads directly from the per-experiment database.
     */
    public static experimentsReadExperiment<ThrowOnError extends boolean = false>(options: Options<ExperimentsReadExperimentData, ThrowOnError>) {
        return (options.client ?? client).get<ExperimentsReadExperimentResponses, ExperimentsReadExperimentErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/experiments/{id}',
            ...options
        });
    }
    
    /**
     * Update Experiment
     *
     * Update an experiment.
     */
    public static experimentsUpdateExperiment<ThrowOnError extends boolean = false>(options: Options<ExperimentsUpdateExperimentData, ThrowOnError>) {
        return (options.client ?? client).put<ExperimentsUpdateExperimentResponses, ExperimentsUpdateExperimentErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/experiments/{id}',
            ...options
        });
    }
}
