// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ExperimentPublic
 */
export type ExperimentPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Instrument
     */
    instrument?: string | null;
    /**
     * Contact Info
     */
    contact_info?: string | null;
    /**
     * Leader Account
     */
    leader_account?: string | null;
    /**
     * Posix Group
     */
    posix_group?: string | null;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Registration Time
     */
    registration_time?: string | null;
    /**
     * Run Count
     */
    run_count?: number;
    /**
     * Players
     */
    players?: Array<string>;
    /**
     * Post Players
     */
    post_players?: Array<string>;
    last_run?: LastRun | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ExperimentsPublic
 */
export type ExperimentsPublic = {
    /**
     * Data
     */
    data: Array<ExperimentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InstrumentSummary
 */
export type InstrumentSummary = {
    /**
     * Instrument
     */
    instrument: string;
    /**
     * Experiment Count
     */
    experiment_count: number;
};

/**
 * LastRun
 */
export type LastRun = {
    /**
     * Num
     */
    num: number;
    /**
     * Begin Time
     */
    begin_time: string;
    /**
     * End Time
     */
    end_time?: string | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

export type PydanticObjectId = string;

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    id: PydanticObjectId;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        user_id: PydanticObjectId;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        user_id: PydanticObjectId;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: PydanticObjectId;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ExperimentsReadExperimentNamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/experiments/names';
};

export type ExperimentsReadExperimentNamesResponses = {
    /**
     * Response Experiments-Read Experiment Names
     *
     * Successful Response
     */
    200: Array<string>;
};

export type ExperimentsReadExperimentNamesResponse = ExperimentsReadExperimentNamesResponses[keyof ExperimentsReadExperimentNamesResponses];

export type ExperimentsReadExperimentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Sort By
         */
        sort_by?: 'name' | 'instrument' | 'leader_account' | 'run_count' | 'start_time' | 'created_at';
        /**
         * Sort Desc
         */
        sort_desc?: boolean;
        /**
         * Instrument
         */
        instrument?: string | null;
    };
    url: '/api/v1/experiments/';
};

export type ExperimentsReadExperimentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExperimentsReadExperimentsError = ExperimentsReadExperimentsErrors[keyof ExperimentsReadExperimentsErrors];

export type ExperimentsReadExperimentsResponses = {
    /**
     * Successful Response
     */
    200: ExperimentsPublic;
};

export type ExperimentsReadExperimentsResponse = ExperimentsReadExperimentsResponses[keyof ExperimentsReadExperimentsResponses];

export type ExperimentsCreateExperimentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/experiments/';
};

export type ExperimentsCreateExperimentResponses = {
    /**
     * Successful Response
     */
    200: ExperimentPublic;
};

export type ExperimentsCreateExperimentResponse = ExperimentsCreateExperimentResponses[keyof ExperimentsCreateExperimentResponses];

export type ExperimentsDeleteExperimentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/experiments/{id}';
};

export type ExperimentsDeleteExperimentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExperimentsDeleteExperimentError = ExperimentsDeleteExperimentErrors[keyof ExperimentsDeleteExperimentErrors];

export type ExperimentsDeleteExperimentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ExperimentsDeleteExperimentResponse = ExperimentsDeleteExperimentResponses[keyof ExperimentsDeleteExperimentResponses];

export type ExperimentsReadExperimentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/experiments/{id}';
};

export type ExperimentsReadExperimentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExperimentsReadExperimentError = ExperimentsReadExperimentErrors[keyof ExperimentsReadExperimentErrors];

export type ExperimentsReadExperimentResponses = {
    /**
     * Successful Response
     */
    200: ExperimentPublic;
};

export type ExperimentsReadExperimentResponse = ExperimentsReadExperimentResponses[keyof ExperimentsReadExperimentResponses];

export type ExperimentsUpdateExperimentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/experiments/{id}';
};

export type ExperimentsUpdateExperimentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExperimentsUpdateExperimentError = ExperimentsUpdateExperimentErrors[keyof ExperimentsUpdateExperimentErrors];

export type ExperimentsUpdateExperimentResponses = {
    /**
     * Successful Response
     */
    200: ExperimentPublic;
};

export type ExperimentsUpdateExperimentResponse = ExperimentsUpdateExperimentResponses[keyof ExperimentsUpdateExperimentResponses];

export type InstrumentsReadInstrumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/instruments/';
};

export type InstrumentsReadInstrumentsResponses = {
    /**
     * Response Instruments-Read Instruments
     *
     * Successful Response
     */
    200: Array<InstrumentSummary>;
};

export type InstrumentsReadInstrumentsResponse = InstrumentsReadInstrumentsResponses[keyof InstrumentsReadInstrumentsResponses];
