// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * InstrumentSummary
 */
export const zInstrumentSummary = z.object({
    instrument: z.string(),
    experiment_count: z.int()
});

/**
 * ItemCreate
 */
export const zItemCreate = z.object({
    title: z.string().min(1).max(255),
    description: z.string().max(255).nullish()
});

/**
 * ItemUpdate
 */
export const zItemUpdate = z.object({
    title: z.string().min(1).max(255).nullish(),
    description: z.string().max(255).nullish()
});

/**
 * LastRun
 */
export const zLastRun = z.object({
    num: z.int(),
    begin_time: z.iso.datetime(),
    end_time: z.iso.datetime().nullish()
});

/**
 * ExperimentPublic
 */
export const zExperimentPublic = z.object({
    name: z.string().min(1).max(255),
    description: z.string().nullish(),
    instrument: z.string().nullish(),
    contact_info: z.string().nullish(),
    leader_account: z.string().nullish(),
    posix_group: z.string().nullish(),
    params: z.record(z.string(), z.unknown()).nullish(),
    start_time: z.iso.datetime().nullish(),
    end_time: z.iso.datetime().nullish(),
    registration_time: z.iso.datetime().nullish(),
    run_count: z.int().optional().default(0),
    players: z.array(z.string()).optional(),
    post_players: z.array(z.string()).optional(),
    last_run: zLastRun.nullish(),
    id: z.string(),
    created_at: z.iso.datetime().nullish()
});

/**
 * ExperimentsPublic
 */
export const zExperimentsPublic = z.object({
    data: z.array(zExperimentPublic),
    count: z.int()
});

/**
 * Message
 */
export const zMessage = z.object({
    message: z.string()
});

export const zPydanticObjectId = z.string().length(24).regex(/^[0-9a-f]{24}$/);

/**
 * ItemPublic
 */
export const zItemPublic = z.object({
    title: z.string().min(1).max(255),
    description: z.string().max(255).nullish(),
    id: zPydanticObjectId,
    owner_id: zPydanticObjectId,
    created_at: z.iso.datetime().nullish()
});

/**
 * ItemsPublic
 */
export const zItemsPublic = z.object({
    data: z.array(zItemPublic),
    count: z.int()
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    email: z.email().max(255),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    id: zPydanticObjectId,
    created_at: z.iso.datetime().nullish()
});

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
    email: z.email().max(255).nullish(),
    is_active: z.boolean().nullish(),
    is_superuser: z.boolean().nullish(),
    full_name: z.string().max(255).nullish()
});

/**
 * UserUpdateMe
 */
export const zUserUpdateMe = z.object({
    full_name: z.string().max(255).nullish(),
    email: z.email().max(255).nullish()
});

/**
 * UsersPublic
 */
export const zUsersPublic = z.object({
    data: z.array(zUserPublic),
    count: z.int()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zUsersReadUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100)
    }).optional()
});

/**
 * Successful Response
 */
export const zUsersReadUsersResponse = zUsersPublic;

export const zUsersDeleteUserMeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersDeleteUserMeResponse = zMessage;

export const zUsersReadUserMeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersReadUserMeResponse = zUserPublic;

export const zUsersUpdateUserMeData = z.object({
    body: zUserUpdateMe,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersUpdateUserMeResponse = zUserPublic;

export const zUsersDeleteUserData = z.object({
    body: z.never().optional(),
    path: z.object({
        user_id: zPydanticObjectId
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersDeleteUserResponse = zMessage;

export const zUsersReadUserByIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        user_id: zPydanticObjectId
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersReadUserByIdResponse = zUserPublic;

export const zUsersUpdateUserData = z.object({
    body: zUserUpdate,
    path: z.object({
        user_id: zPydanticObjectId
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersUpdateUserResponse = zUserPublic;

export const zUtilsHealthCheckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Utils-Health Check
 *
 * Successful Response
 */
export const zUtilsHealthCheckResponse = z.boolean();

export const zItemsReadItemsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100)
    }).optional()
});

/**
 * Successful Response
 */
export const zItemsReadItemsResponse = zItemsPublic;

export const zItemsCreateItemData = z.object({
    body: zItemCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zItemsCreateItemResponse = zItemPublic;

export const zItemsDeleteItemData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: zPydanticObjectId
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zItemsDeleteItemResponse = zMessage;

export const zItemsReadItemData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: zPydanticObjectId
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zItemsReadItemResponse = zItemPublic;

export const zItemsUpdateItemData = z.object({
    body: zItemUpdate,
    path: z.object({
        id: zPydanticObjectId
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zItemsUpdateItemResponse = zItemPublic;

export const zExperimentsReadExperimentNamesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Experiments-Read Experiment Names
 *
 * Successful Response
 */
export const zExperimentsReadExperimentNamesResponse = z.array(z.string());

export const zExperimentsReadExperimentsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100),
        sort_by: z.enum([
            'name',
            'instrument',
            'leader_account',
            'run_count',
            'start_time',
            'created_at'
        ]).optional(),
        sort_desc: z.boolean().optional().default(false),
        instrument: z.string().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zExperimentsReadExperimentsResponse = zExperimentsPublic;

export const zExperimentsCreateExperimentData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zExperimentsCreateExperimentResponse = zExperimentPublic;

export const zExperimentsDeleteExperimentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zExperimentsDeleteExperimentResponse = zMessage;

export const zExperimentsReadExperimentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zExperimentsReadExperimentResponse = zExperimentPublic;

export const zExperimentsUpdateExperimentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zExperimentsUpdateExperimentResponse = zExperimentPublic;

export const zInstrumentsReadInstrumentsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Instruments-Read Instruments
 *
 * Successful Response
 */
export const zInstrumentsReadInstrumentsResponse = z.array(zInstrumentSummary);
