// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ExperimentPublic
 */
export const zExperimentPublic = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullable(),
    start_time: z.iso.datetime(),
    end_time: z.iso.datetime().nullable(),
    instrument_id: z.uuid().nullable(),
    legacy_id: z.string().nullable(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * ExperimentsPublic
 */
export const zExperimentsPublic = z.object({
    data: z.array(zExperimentPublic),
    count: z.int()
});

/**
 * InstrumentSummary
 */
export const zInstrumentSummary = z.object({
    instrument_id: z.uuid().nullable(),
    experiment_count: z.int()
});

/**
 * Message
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    id: z.uuid(),
    username: z.string(),
    display_name: z.string().nullable(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
    display_name: z.string().nullish()
});

/**
 * UserUpdateMe
 */
export const zUserUpdateMe = z.object({
    display_name: z.string().nullish()
});

/**
 * UsersPublic
 */
export const zUsersPublic = z.object({
    data: z.array(zUserPublic),
    count: z.int()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zUsersReadUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100)
    }).optional()
});

/**
 * Successful Response
 */
export const zUsersReadUsersResponse = zUsersPublic;

export const zUsersDeleteUserMeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersDeleteUserMeResponse = zMessage;

export const zUsersReadUserMeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersReadUserMeResponse = zUserPublic;

export const zUsersUpdateUserMeData = z.object({
    body: zUserUpdateMe,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersUpdateUserMeResponse = zUserPublic;

export const zUsersDeleteUserData = z.object({
    body: z.never().optional(),
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersDeleteUserResponse = zMessage;

export const zUsersReadUserByIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersReadUserByIdResponse = zUserPublic;

export const zUsersUpdateUserData = z.object({
    body: zUserUpdate,
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUsersUpdateUserResponse = zUserPublic;

export const zUtilsHealthCheckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Utils-Health Check
 *
 * Successful Response
 */
export const zUtilsHealthCheckResponse = z.boolean();

export const zExperimentsReadExperimentNamesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Experiments-Read Experiment Names
 *
 * Successful Response
 */
export const zExperimentsReadExperimentNamesResponse = z.array(z.string());

export const zExperimentsReadExperimentsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100),
        sort_by: z.enum([
            'name',
            'start_time',
            'end_time',
            'created_at'
        ]).optional(),
        sort_desc: z.boolean().optional().default(false),
        instrument_id: z.uuid().nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zExperimentsReadExperimentsResponse = zExperimentsPublic;

export const zExperimentsCreateExperimentData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zExperimentsCreateExperimentResponse = zExperimentPublic;

export const zExperimentsDeleteExperimentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zExperimentsDeleteExperimentResponse = zMessage;

export const zExperimentsReadExperimentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zExperimentsReadExperimentResponse = zExperimentPublic;

export const zExperimentsUpdateExperimentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zExperimentsUpdateExperimentResponse = zExperimentPublic;

export const zInstrumentsReadInstrumentsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Instruments-Read Instruments
 *
 * Successful Response
 */
export const zInstrumentsReadInstrumentsResponse = z.array(zInstrumentSummary);
