/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutExperimentsRouteImport } from './routes/_layout/experiments'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutExperimentsIndexRouteImport } from './routes/_layout/experiments/index'
import { Route as LayoutExperimentsInstrumentRouteImport } from './routes/_layout/experiments/$instrument'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperimentsRoute = LayoutExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperimentsIndexRoute = LayoutExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutExperimentsRoute,
} as any)
const LayoutExperimentsInstrumentRoute =
  LayoutExperimentsInstrumentRouteImport.update({
    id: '/$instrument',
    path: '/$instrument',
    getParentRoute: () => LayoutExperimentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/admin': typeof LayoutAdminRoute
  '/experiments': typeof LayoutExperimentsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/experiments/$instrument': typeof LayoutExperimentsInstrumentRoute
  '/experiments/': typeof LayoutExperimentsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/experiments/$instrument': typeof LayoutExperimentsInstrumentRoute
  '/experiments': typeof LayoutExperimentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/experiments': typeof LayoutExperimentsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/experiments/$instrument': typeof LayoutExperimentsInstrumentRoute
  '/_layout/experiments/': typeof LayoutExperimentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/experiments'
    | '/settings'
    | '/experiments/$instrument'
    | '/experiments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/settings' | '/' | '/experiments/$instrument' | '/experiments'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/admin'
    | '/_layout/experiments'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/experiments/$instrument'
    | '/_layout/experiments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experiments': {
      id: '/_layout/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof LayoutExperimentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experiments/': {
      id: '/_layout/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof LayoutExperimentsIndexRouteImport
      parentRoute: typeof LayoutExperimentsRoute
    }
    '/_layout/experiments/$instrument': {
      id: '/_layout/experiments/$instrument'
      path: '/$instrument'
      fullPath: '/experiments/$instrument'
      preLoaderRoute: typeof LayoutExperimentsInstrumentRouteImport
      parentRoute: typeof LayoutExperimentsRoute
    }
  }
}

interface LayoutExperimentsRouteChildren {
  LayoutExperimentsInstrumentRoute: typeof LayoutExperimentsInstrumentRoute
  LayoutExperimentsIndexRoute: typeof LayoutExperimentsIndexRoute
}

const LayoutExperimentsRouteChildren: LayoutExperimentsRouteChildren = {
  LayoutExperimentsInstrumentRoute: LayoutExperimentsInstrumentRoute,
  LayoutExperimentsIndexRoute: LayoutExperimentsIndexRoute,
}

const LayoutExperimentsRouteWithChildren =
  LayoutExperimentsRoute._addFileChildren(LayoutExperimentsRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutExperimentsRoute: typeof LayoutExperimentsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutExperimentsRoute: LayoutExperimentsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
